chore(deps): update nest to v9
SoftwareBrothers/adminjs-nestjs pull request #42
Opened 2022-07-17 16:43 UTC by serembon

Updated Nestjs deps to v9

2022-08-04 12:06 UTC, dziraf requested changes

2022-08-04 18:34 UTC, serembon commented on package.json
> +    "@nestjs/common": "^9.0.5",
Fixed

2022-08-04 18:34 UTC, serembon commented on package.json
> +  "version": "5.0.1",
Fixed, too

2022-08-12 06:42 UTC, dziraf approved these changes

2022-08-12 06:45 UTC, merged